# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false
env:
  - SPHINX_SPEC="Sphinx==1.2.3"
  - SPHINX_SPEC="Sphinx"
matrix:
  include:
    - python: 3.6
    - python: 2.7
      env:
        - SPHINXOPTS='-W'
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - sudo apt-get install texlive texlive-latex-extra latexmk
  - pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
  - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --trusted-host wheels.astropy.org --trusted-host wheels2.astropy.org --use-wheel nose numpy matplotlib ${SPHINX_SPEC}
script:
  - |
    python setup.py sdist
    cd dist
    pip install numpydoc* -v
  - nosetests numpydoc
  - |
    cd ../doc
    make SPHINXOPTS=$SPHINXOPTS html
    make SPHINXOPTS=$SPHINXOPTS latexpdf
